[package]
name = "docker-shiplift"
version = "0.1.0"
authors = ["V.M. Dogiparthi <dvijaymanohar@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
url = "2.1"
shiplift = "0.6"
yaml-rust = "0.4"
