[workspace]
members = [
    "acpid",
    "ahcid",
    "alxd",
    "bgad",
    "block-io-wrapper",
    "e1000d",
    "ided",
    "ihdad",
    "ixgbed",
    "nvmed",
    "pcid",
    "pcspkrd",
    "ps2d",
    "rtl8168d",
    "vboxd",
    "vesad",
    "xhcid",
    "usbctl",
    "usbhidd",
    "usbscsid",
]

[patch.crates-io]
mio = { git = "https://gitlab.redox-os.org/redox-os/mio.git", branch = "redox-unix" }
net2 = { git = "https://gitlab.redox-os.org/redox-os/net2-rs.git", branch = "master" }
orbclient = { git = "https://gitlab.redox-os.org/redox-os/orbclient.git", version = "0.3.28" }
