[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["V.M. Dogiparthi <dvijaymanohar@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.9.0"

[dependencies.diesel]
version = "1.0.0"
features = ["postgres"]
